/*DECLARE @EMPRESA INT
SET @EMPRESA = 2
UPDATE CONTASARECEBER SET NUMENTRADADEV = NULL WHERE CODEMPRESA = @EMPRESA
UPDATE NFENTRADA SET NUMSAIDAORIGEM = NULL WHERE CODEMPRESA = @EMPRESA
UPDATE NFSAIDA SET NUMENTRADAORIGEM = NULL WHERE CODEMPRESA = @EMPRESA
UPDATE NFSAIDA SET NUMPEDVENDA = NULL WHERE NUMPEDVENDA IS NOT NULL AND CODEMPRESA = @EMPRESA
update CONTASARECEBER set NUMACERTO=null WHERE CODEMPRESA = @EMPRESA
update CABPEDVENDA set NUMCARGA=null WHERE CODEMPRESA = @EMPRESA
update PREDEV set NUMPEDIDOORIGEM=null WHERE CODEMPRESA = @EMPRESA
UPDATE PESSOA SET CODEMPRESA=1 WHERE CODEMPRESA=@EMPRESA
UPDATE CXBANCO SET CODEMPRESA=1 WHERE CODEMPRESA=@EMPRESA
UPDATE PCPFORMULAMATRIZ SET CODEMPRESA=1 WHERE CODEMPRESA=@EMPRESA
UPDATE CONTASARECEBER_MOVCXBCO SET NUMLANCAMENTO =NULL WHERE NUMLANCAMENTO IN (SELECT NUMLANCAMENTO FROM CONTASARECEBER WHERE CODEMPRESA=@EMPRESA)
UPDATE CONTASARECEBER SET NUMACERTO = NULL WHERE NUMACERTO IN (SELECT ID FROM ACERTOCAIXA WHERE CODEMPRESA = @empresa)
UPDATE CONTASARECEBER SET NUMACERTO = NULL WHERE CODEMPRESA = @empresa 
UPDATE CONTASARECEBER SET NUMCARGA=NULL WHERE CODEMPRESA=@EMPRESA
UPDATE NIVEL_EMPRESA SET CODNIVEL = 1 WHERE CODEMPRESA=@EMPRESA
UPDATE A
SET A.NUMCARGA = (SELECT TOP 1 NUMCARGA FROM CARREGAMENTO WHERE CODEMPRESA =1)
FROM CONTASARECEBER A
INNER JOIN CARREGAMENTO B ON A.NUMCARGA = B.NUMCARGA
WHERE B.CODEMPRESA =@EMPRESA*/

use base_aa
declare @EMPRESA int
set @EMPRESA = 2

--ALTER TABLE NIVEL_EMPRESA NOCHECK CONSTRAINT FK_6rh6qyfsolxurjklb9kv8t32v

DELETE FROM CONTASAPAGAR_MOVCXBCO WHERE NUMTRANSACAO IN (SELECT NUMTRANSACAO FROM MOVCXBCO WHERE CODEMPRESA=@EMPRESA);
DELETE FROM CONTASARECEBER_MOVCXBCO WHERE NUMTRANSACAO IN (SELECT NUMTRANSACAO FROM MOVCXBCO WHERE CODEMPRESA=@EMPRESA);
DELETE FROM ADIANTAMENTO WHERE CODTITULO IN (SELECT CODTITULO FROM CONTASAPAGAR WHERE CODEMPRESA=@EMPRESA);
DELETE FROM CABPEDVENDA_COMPLEMENTOS WHERE NUMPEDIDO IN ( SELECT NUMPEDIDO FROM CABPEDVENDA WHERE CODEMPRESA=@EMPRESA);
DELETE FROM ITEMPEDVENDA WHERE NUMPEDIDO IN (SELECT NUMPEDIDO FROM CABPEDVENDA WHERE CODEMPRESA=@EMPRESA);
DELETE FROM COMISSAO WHERE NUMNFESAIDA IN (SELECT NUMNFESAIDA FROM NFSAIDA WHERE CODEMPRESA=@EMPRESA);
DELETE FROM MOVIMENTACAO WHERE NUMSAIDA IN (SELECT NUMSAIDA FROM NFSAIDA WHERE CODEMPRESA=@EMPRESA);
DELETE FROM LOGDESDCRECEBER WHERE CODCRECEBER IN (SELECT CODCRECEBER FROM CONTASARECEBER WHERE CODEMPRESA=@EMPRESA);
DELETE FROM CONTASARECEBER WHERE NUMSAIDA IN (SELECT NUMSAIDA FROM NFSAIDA WHERE CODEMPRESA=@EMPRESA);
DELETE FROM NFENTRADA_COMPLEMENTOS WHERE NUMENTRADA IN (SELECT NUMENTRADA FROM NFENTRADA WHERE CODEMPRESA=@EMPRESA);
DELETE FROM MOVIMENTACAO WHERE NUMENTRADA IN (SELECT NUMENTRADA FROM NFENTRADA WHERE CODEMPRESA=@EMPRESA);
DELETE FROM ADIANTAMENTO_CONTASAPAGAR WHERE NUMCPAGAR IN (SELECT NUMCPAGAR FROM CONTASAPAGAR WHERE CODEMPRESA=@EMPRESA);
DELETE FROM CONTASAPAGAR_MOVCXBCO WHERE NUMLANCAMENTO IN (SELECT NUMLANCAMENTO FROM CONTASAPAGAR WHERE CODEMPRESA=@EMPRESA);
DELETE FROM LOGDESDCPAGAR WHERE CODCPAGAR IN (SELECT CODCPAGAR FROM CONTASAPAGAR WHERE CODEMPRESA=@EMPRESA);
DELETE FROM CONTASAPAGAR WHERE NUMENTRADA IN (SELECT NUMENTRADA FROM NFENTRADA WHERE CODEMPRESA=@EMPRESA);

DELETE FROM NIVEL_EMPRESA WHERE CODEMPRESA = @EMPRESA
DELETE FROM MOVIMENTACAO WHERE CODEMPRESA=@EMPRESA;
DELETE FROM ADIANTAMENTO WHERE CODEMPRESA=@EMPRESA;
DELETE FROM MOVCXBCO WHERE CODEMPRESA=@EMPRESA;
DELETE FROM MOVIMENTACAO WHERE CODEMPRESAPRECO=@EMPRESA;
DELETE FROM PRECOTABELA WHERE CODEMPRESAPRECO=@EMPRESA;
DELETE FROM PRECO_ESTOQUE WHERE CODEMPRESA=@EMPRESA;
DELETE FROM LOGINUTNFE WHERE CODEMPRESA=@EMPRESA;
DELETE FROM CONTASARECEBER WHERE CODEMPRESA=@EMPRESA;
DELETE FROM CONTASAPAGAR WHERE CODEMPRESA=@EMPRESA;
DELETE FROM CABPEDVENDA WHERE CODEMPRESA=@EMPRESA;
DELETE FROM NFSAIDA WHERE CODEMPRESA=@EMPRESA;
DELETE FROM LOGPRECIFICACAO WHERE CODEMPRESA=@EMPRESA;
DELETE FROM ADIANTAMENTO_HISTMOV WHERE CODEMPRESA=@EMPRESA;
DELETE FROM EMPRESA_COMPLEMENTOS WHERE CODEMPRESA=@EMPRESA;
DELETE FROM NFENTRADA WHERE CODEMPRESA=@EMPRESA;
DELETE FROM EMPRESA WHERE CODIGO=@EMPRESA;

--ALTER TABLE NIVEL_EMPRESA CHECK CONSTRAINT FK_6rh6qyfsolxurjklb9kv8t32v
select * from NIVEL_EMPRESA
