DECLARE @EMPRESA INT
SET @EMPRESA = 1
UPDATE CONTASARECEBER SET NUMENTRADADEV = NULL
UPDATE NFENTRADA SET NUMSAIDAORIGEM = NULL
UPDATE NFSAIDA SET NUMENTRADAORIGEM = NULL
UPDATE NFSAIDA SET NUMPEDVENDA = NULL WHERE NUMPEDVENDA IS NOT NULL
update CONTASARECEBER set NUMACERTO=null
update CABPEDVENDA set NUMCARGA=null
update PREDEV set NUMPEDIDOORIGEM=null
GO
DECLARE @EMPRESA INT
SET @EMPRESA = 1
/*--------------------------------------------------------------------------*/
/* TIVE QUE APAGAR A TABELA CARTA CORRE��O, APESAR DE ELA N�O TER EMPRESA 2 */
DELETE FROM CARTACORRECAO 
/*--------------------------------------------------------------------------*/
DELETE FROM MOVIMENTACAO					WHERE CODEMPRESA=		@EMPRESA
DELETE FROM ADIANTAMENTO_HISTMOV			   	WHERE CODEMPRESA=		@EMPRESA
DELETE FROM ACERTOCAIXA						WHERE CODEMPRESA=		@EMPRESA
DELETE FROM ACERTOCAIXA						WHERE CODEMPRESA=		@EMPRESA
DELETE FROM CONTASARECEBER_MOVCXBCO				WHERE NUMLANCAMENTO		in (select NUMLANCAMENTO FROM CONTASARECEBER WHERE CODEMPRESA=@EMPRESA)
DELETE FROM LOGDESDCRECEBER					WHERE CODEMPRESA=		@EMPRESA
DELETE FROM CONTASARECEBER					WHERE CODEMPRESA=		@EMPRESA
DELETE FROM COMISSAO						WHERE CODEMPRESA=		@EMPRESA
DELETE FROM NFSAIDA_COMPLEMENTOS				WHERE NUMSAIDA			IN (SELECT NUMSAIDA FROM NFSAIDA WHERE CODEMPRESA=@EMPRESA)
DELETE FROM NFSAIDA						WHERE CODEMPRESA=		@EMPRESA
delete from CARREGAMENTO					WHERE CODEMPRESA=		@EMPRESA
DELETE from CARREGAMENTO_COMPLEMENTOS				WHERE NUMCARGA			IN (SELECT NUMCARGA FROM CARREGAMENTO WHERE CODEMPRESA=@EMPRESA)
DELETE FROM OSINVENTARIOITENS					WHERE CODEMPRESA=		@EMPRESA
DELETE FROM OSINVENTARIO					WHERE CODEMPRESA=		@EMPRESA
DELETE FROM CONTROLECAIXA_CARGAITENS				WHERE NUMCARGA			IN (SELECT NUMCARGA FROM CARREGAMENTO WHERE CODEMPRESA=@EMPRESA)
DELETE FROM CONTROLECAIXA_CARGA					WHERE NUMCARGA			IN (SELECT NUMCARGA FROM CARREGAMENTO WHERE CODEMPRESA=@EMPRESA)
DELETE FROM ITEMPEDCOMPRA					WHERE NUMPEDIDO			IN (SELECT NUMPEDIDO FROM CABPEDVENDA WHERE CODEMPRESA=@EMPRESA)
DELETE FROM CABPEDVENDA_COMPLEMENTOS				WHERE NUMPEDIDO			IN (SELECT NUMPEDIDO FROM CABPEDVENDA WHERE CODEMPRESA=@EMPRESA)
DELETE FROM CABPEDCOMPRA					WHERE CODEMPRESA=		@EMPRESA
DELETE FROM LOGPEDIDOFV						WHERE NUMPEDIDOERP		IN (SELECT NUMPEDIDO FROM CABPEDVENDA WHERE CODEMPRESA=@EMPRESA)
DELETE FROM ATENDIMENTOVISITACLIENTE				WHERE NUMPEDVENDA		IN (SELECT NUMPEDIDO FROM CABPEDVENDA WHERE CODEMPRESA=@EMPRESA)
DELETE FROM CARGA_PEDIDO					WHERE NUMPEDIDO			IN (SELECT NUMPEDIDO FROM CABPEDVENDA WHERE CODEMPRESA=@EMPRESA)
DELETE FROM ITEMPEDVENDA					WHERE CODEMPRESAPRECO=	@EMPRESA
DELETE FROM CABPEDVENDA						WHERE CODEMPRESA=		@EMPRESA
DELETE FROM CPFNANOTA						WHERE NUMSAIDA			IN (SELECT NUMSAIDA FROM NFSAIDA WHERE CODEMPRESA=@EMPRESA)
DELETE FROM INFDOCMDFE						WHERE NUMSAIDA			IN (SELECT NUMSAIDA FROM NFSAIDA WHERE CODEMPRESA=@EMPRESA)
DELETE FROM ROTERIZACAOCARREGAMENTO				WHERE NUMCARGA			IN (SELECT NUMCARGA FROM CARREGAMENTO WHERE CODEMPRESA=@EMPRESA)
DELETE FROM ACOMPANHAMENTOENTREGAVEICULO			WHERE NUMCARGA			IN (SELECT NUMCARGA FROM CARREGAMENTO WHERE CODEMPRESA=@EMPRESA)
DELETE FROM CARTACORRECAO					WHERE CODEMPRESA=		@EMPRESA
DELETE FROM ADIANTAMENTO_CONTASAPAGAR				WHERE NUMCPAGAR			IN (select numnota from CONTASAPAGAR where CONTASAPAGAR.CODEMPRESA=@empresa)
DELETE FROM ADIANTAMENTO					WHERE CODEMPRESA=		@EMPRESA
DELETE FROM LOGDESDCPAGAR					WHERE CODEMPRESA=		@EMPRESA
DELETE FROM CONTASAPAGAR_MOVCXBCO				WHERE NUMLANCAMENTO		IN (select NUMLANCAMENTO from CONTASAPAGAR where CODEMPRESA=@empresa)
DELETE FROM CONTASAPAGAR					WHERE CODEMPRESA=		@EMPRESA
DELETE FROM NFENTRADA_COMPLEMENTOS				WHERE NUMENTRADA		IN (SELECT NUMENTRADA FROM NFENTRADA WHERE CODEMPRESA=@EMPRESA)
DELETE FROM PREDEV_ITEM_OCORRENCIA
DELETE FROM PREDEV_ITEM
DELETE FROM PREDEV
DELETE FROM NFENTRADA						WHERE CODEMPRESA=		@EMPRESA
DELETE FROM COMISSAO						WHERE CODEMPRESA=		@EMPRESA
DELETE FROM CREDCLIENTE						WHERE CODEMPRESA=		@EMPRESA
DELETE FROM CAIXA_TITULO					WHERE CODTITULO			IN (SELECT NUMNOTA FROM MOVIMENTACAO WHERE CODEMPRESA=@EMPRESA)
DELETE FROM LOGDESDCRECEBER					WHERE CODEMPRESA		=@EMPRESA
DELETE FROM CONTASARECEBER					WHERE CODEMPRESA		=@EMPRESA
DELETE FROM NFSAIDA_COMPLEMENTOS				WHERE NUMSAIDA			IN (SELECT NUMSAIDA FROM NFSAIDA WHERE CODEMPRESA=@EMPRESA)
DELETE FROM NFSAIDA						WHERE CODEMPRESA=		@EMPRESA
DELETE FROM MOVIMENTACAO					WHERE CODEMPRESA=		@EMPRESA
DELETE FROM CONTASARECEBER_MOVCXBCO				WHERE NUMTRANSACAO		IN (select NUMTRANSACAO from CONTASARECEBER where CODEMPRESA=@empresa)
DELETE FROM MOVCXBCO						WHERE CODEMPRESA=		@EMPRESA
--DELETE FROM PCPOPAGREGADO
--DELETE FROM PCPOP
--DELETE FROM PCPFORMULAAGREGADO	--- Apaga as f�rmulas
--DELETE FROM PCPFORMULAMATRIZ		--- Apaga as f�rmulas
--DELETE FROM PRECOTABELA WHERE CODEMPRESAPRECO <> @EMPRESA
--DELETE FROM PRECO_ESTOQUE WHERE CODEMPRESA <> @EMPRESA
--DELETE FROM PREDEV_ITEM_OCORRENCIA
--DELETE FROM PREDEV_ITEM 
--DELETE FROM PREDEV 
--DELETE FROM CUPOMSITEF --- SE A EMPRESA TIVER NFCE
--DELETE FROM POSNFCE    --- SE A EMPRESA TIVER NFCE
