--PIS/COFINS

DECLARE @NATORIG INT
DECLARE @NATDEST INT
SET @NATORIG = 2
  -- Copia
SET @NATDEST = 5
  -- Cola

INSERT INTO TRIBUTACAOPISCOFINS (PERBASECALCULOCOFINS, PERBASECALCULOPIS, PERBASECALCULOSTCOFINS, PERBASECALCULOSTPIS,
PERCOFINS, PERPIS, PERSTCOFINS, PERSTPIS, CSTCOFINS, CSTPIS, GRUPOPISCOFINS, 
NATUREZAOPERACAO, DTULTALTERACAO)
(SELECT PERBASECALCULOCOFINS, PERBASECALCULOPIS, PERBASECALCULOSTCOFINS, PERBASECALCULOSTPIS,
PERCOFINS, PERPIS, PERSTCOFINS, PERSTPIS, CSTCOFINS, CSTPIS, GRUPOPISCOFINS, 
@NATDEST, DTULTALTERACAO FROM TRIBUTACAOPISCOFINS WHERE NATUREZAOPERACAO = @NATORIG)


--IPI

DECLARE @NATORIG INT
DECLARE @NATDEST INT
SET @NATORIG = 2
  -- Copia
SET @NATDEST = 5
  -- Cola

INSERT INTO TRIBUTACAOIPI (PERCENTUALBASECALCULO, PERCENTUALIPI, VALORUNIDADEIPI, CSTIPI, GRUPOIPI,
NATUREZAOPERACAO, DTULTALTERACAO)
(SELECT PERCENTUALBASECALCULO, PERCENTUALIPI, VALORUNIDADEIPI, CSTIPI, GRUPOIPI,
@NATDEST, DTULTALTERACAO FROM TRIBUTACAOIPI WHERE NATUREZAOPERACAO = @NATORIG)


--ICMS

DECLARE @NATORIG INT
DECLARE @NATDEST INT
SET @NATORIG = 2
  -- Copia
SET @NATDEST = 5
  -- Cola

INSERT INTO TRIBUTACAOICMS (PERCFCPDEST,PERCINTERESTADUAL,PERCINTERNADEST, PERCPARTILHA, OBSERVACAO, PERCENTUALBASECALCULO,
PERCENTUALBASECALCULOST,PERCENTUALCREDITOSIMPLES,PERCENTUALDIFERIMENTO,PERCENTUALICMS,PERCENTUALICMSST,PERCENTUALINTERNO,PERCENTUALMVA,
PERCPARTILHADEST,PERCPARTILHAREMET,VALORPAUTA,CFOP,CSOSN,CST,GRUPOICMS,MODALIDADEBASECALCULO,MODALIDADEBASECALCULOST,NATUREZAOPERACAO,
ORIGEM,TIPOCALCULO,UF,DTULTALT)
(SELECT PERCFCPDEST, PERCINTERESTADUAL, PERCINTERNADEST, PERCPARTILHA, OBSERVACAO, PERCENTUALBASECALCULO, PERCENTUALBASECALCULOST,
PERCENTUALCREDITOSIMPLES, PERCENTUALDIFERIMENTO, PERCENTUALICMS, PERCENTUALICMSST, PERCENTUALINTERNO, PERCENTUALMVA, PERCPARTILHADEST, 
PERCPARTILHAREMET, VALORPAUTA, CFOP, CSOSN, CST, GRUPOICMS, MODALIDADEBASECALCULO, MODALIDADEBASECALCULOST, @NATDEST, ORIGEM,
TIPOCALCULO, UF, DTULTALT FROM TRIBUTACAOICMS WHERE NATUREZAOPERACAO = @NATORIG)
