UPDATE PESSOAUSUARIOB2B SET SENHA = 'E/SwuobwJ5oCDlYdXo0zaQ==' WHERE SENHA IS NOT NULL

--- Script pra padronizar a senha:
USE [base_aa]
GO

IF OBJECT_ID('tempdb..#PESSOAUSUARIOB2B_NOVO') IS NOT NULL
BEGIN
    DROP TABLE #PESSOAUSUARIOB2B_NOVO;
END

GO
CREATE TABLE #PESSOAUSUARIOB2B_NOVO (
ATIVO INT,
SENHA VARCHAR(MAX),
USUARIO VARCHAR(14),
CODPESSOA INT)
GO
WITH CTE AS (
  SELECT CNPJ
  FROM PESSOA
  WHERE CODREGIAO IS NOT NULL
    AND CODCIDADE IS NOT NULL
  GROUP BY CNPJ
  HAVING COUNT(*) = 1
)

INSERT INTO #PESSOAUSUARIOB2B_NOVO(ATIVO, SENHA, USUARIO, CODPESSOA)
SELECT ATIVO, 'cRwC4EeQr8+YWUEe8a1bTQ==', CNPJ, CODIGO
FROM PESSOA
WHERE CODREGIAO IS NOT NULL
  AND CODCIDADE IS NOT NULL
  AND CNPJ IN (SELECT CNPJ FROM CTE);
GO 

UPDATE P1
SET P1.ATIVO = P2.ATIVO,
    P1.SENHA = P2.SENHA,
    P1.USUARIO = P2.USUARIO
FROM PESSOAUSUARIOB2B P1
INNER JOIN #PESSOAUSUARIOB2B_NOVO P2 ON P1.CODPESSOA = P2.CODPESSOA;

INSERT INTO PESSOAUSUARIOB2B (ATIVO, SENHA, USUARIO, CODPESSOA)
SELECT P2.ATIVO, P2.SENHA, P2.USUARIO, P2.CODPESSOA
FROM #PESSOAUSUARIOB2B_NOVO P2
WHERE NOT EXISTS (SELECT 1 FROM PESSOAUSUARIOB2B WHERE CODPESSOA = P2.CODPESSOA);
---
