DECLARE @CODTABELA INT; 
DECLARE @CODEMPRESA INT; 
DECLARE @CODCLIENTE INT;

SET @CODCLIENTE = 22283 /** AQUI VOCÊ DEVERÁ INSERIR O CÓDIGO DO CLIENTE **/
SET @CODEMPRESA = (SELECT PES.CODEMPRESA FROM PESSOA PES WITH (NOLOCK) WHERE PES.CODIGO = @CODCLIENTE) 
SET @CODTABELA = (SELECT PES.CODTABELA FROM PESSOA PES WITH (NOLOCK) WHERE PES.CODIGO = @CODCLIENTE) 
		 
SELECT P.CODIGO, P.NOME, ISNULL(P.DEPARTAMENTO, 0) AS CODDEP, P.ACEITAVENDAFRACIONADA, P.CODBARRA, P.OBSERVACAO, PT.PRECOCONSUMIDOR, 
ISNULL(PE.QTDISPONIVEL, 0) QTDISPONIVEL, ISNULL(PT.PRECOOFERTA, 0) AS PRECOOFERTA, 
CASE WHEN PT.PRECOOFERTAATIVO = 1 AND PT.PRECOOFERTA > 0 AND PT.DTVALIDADEPRECOOFERTA > GETDATE() THEN 1 ELSE 0 END AS PRECOOFERTAATIVO, 
(SELECT COUNT(*) AS QTDE FROM DESCONTOQUANTIDADE D WITH (NOLOCK) 
	WHERE D.CODPRODUTO = P.CODIGO 
	AND D.CODEMPRESA = CODEMPRESA    
	AND D.CODTABELA = @CODTABELA  
	AND D.STATUS = 'A' 
) AS DESC_QTDE, 
ISNULL((SELECT TOP(1) NP.VLDESCONTO  
	FROM NEGOCIACAOPORPERIODO NP WITH (NOLOCK)  
		WHERE NP.STATUS = 'A'  
		AND NP.CODCLIENTE = @CODCLIENTE 
		AND NP.CODEMPRESA = @CODEMPRESA  
		AND NP.CODPRODUTO = P.CODIGO 
		AND CONVERT(CHAR(10), NP.DTINICIO, 120) <= CONVERT(CHAR(10), GETDATE(), 120) 
		AND CONVERT(CHAR(10), NP.DTFIM, 120) >= CONVERT(CHAR(10), GETDATE(), 120) 
), 0) AS VL_NEG_PERIODO, PT.CODPRECOTAB, ISNULL(P.PESOBRUTO, 0) AS PESOBRUTO, ISNULL(P.PESOLIQUIDO, 0) AS PESOLIQUIDO, 
PE.CODGRUPOIPI, PE.CODGRUPOICMS 
	FROM PRODUTO P WITH (NOLOCK), PRODUTO_COMPLEMENTOS PC WITH (NOLOCK), PRECO_ESTOQUE PE WITH (NOLOCK), PRECOTABELA PT WITH (NOLOCK) 
		WHERE P.CODIGO = PC.CODPRODUTO 
		AND PT.CODPRODUTOPRECO = P.CODIGO 
		AND PT.CODEMPRESAPRECO = PE.CODEMPRESA 
		AND P.ATIVO = 1 
		AND P.STATUS <> 'C' 
		AND ISNULL(PT.PRECOCONSUMIDOR, 0) > 0 
		AND PC.ENVIAECOMERCI = 1 
		AND PE.CODPRODUTO = P.CODIGO 
		AND P.DEPARTAMENTO IS NOT NULL 
		AND PE.CODEMPRESA = @CODEMPRESA  
		AND PT.CODTABELA = @CODTABELA 
ORDER BY P.NOME ASC 


/*** CASO TENHA ALGUNS PRODUTOS QUE NÃO CONTENHAM RELAÇÃO COM A TABELA PRODUTO_COMPLEMENTOS, RODE ESSA SQL ABAIXO
INSERT INTO [dbo].[PRODUTO_COMPLEMENTOS]
           ([ISGTIN]
           ,[OBSERVACAO2]
           ,[CODPRODUTO]
           ,[PERMITEINFQTCONF]
           ,[APELIDO]
           ,[ENVIAECOMERCI]
           ,[INFNUTRICIONAL]
           ,[ISCOMODATO]
           ,[QTUNCX]
		   ,METROQUADRADO)

SELECT
	IIF(CODBARRA IS NULL,0,1),
	NULL,
	CODIGO,
	1,
	NULL,
	0,
	NULL,
	0,
	NULL,
	0
FROM PRODUTO where CODIGO not in (select codproduto from PRODUTO_COMPLEMENTOS)

*/
